/**
 * VAULTX AI Red Team
 *
 * Core promise from the product roadmap: "findings route through the
 * same triage queue your human researchers already use." This module
 * is what makes that literally true — a completed scan doesn't produce
 * a separate report, it produces real rows in `submissions`, attributed
 * to a system AI agent profile, that a human triager accepts/rejects
 * exactly like any researcher's report.
 *
 * Honesty note: this performs AI-assisted STATIC analysis (for
 * github_repo targets, reusing the Week 6 GitHub client) or AI-assisted
 * THREAT MODELING from a written description (for scope_description
 * targets) — not live network exploitation. There's no real attack
 * tooling in a zero-cost stack, and claiming otherwise would be
 * dishonest. The UI copy on the target pages says this explicitly.
 */

import { callClaude, parseJsonResponse } from "@/lib/ai/claude";
import { createAdminClient }from "@/lib/supabase/admin";
import {
  parseGithubUrl, fetchRepoMetadata, fetchRepoTree,
  selectPriorityFiles, fetchFiles,
} from "@/lib/github/client";
import { randomUUID, createHash } from "crypto";
import type { SeverityLevel } from "@/lib/supabase/types";

/**
 * IMPORTANT — authorization model for this module:
 *
 * Every function below uses the service-role admin client, NOT the
 * session-bound client, and therefore bypasses RLS entirely. This is
 * deliberate: runRedTeamScan() is invoked from two places —
 *   1. Interactive server actions (createTarget, triggerScan in
 *      app/actions/red-team.ts), which verify the caller owns the
 *      target's org BEFORE calling into this module
 *   2. The scheduled cron route (app/api/red-team/run-scheduled-scans),
 *      which has no user session at all — it's authenticated via
 *      VAULT_INTERNAL_SECRET instead, not a logged-in user
 *
 * In both cases, by the time code in this file runs, authorization has
 * already happened at the caller. If you add a new caller of
 * runRedTeamScan() or the getOrCreate* helpers, it is YOUR
 * responsibility to verify the caller is authorized first — these
 * functions will not stop you from scanning a target you don't own.
 */

const SYSTEM_AGENT_USERNAME = "vaultx-ai-red-team";
const SYSTEM_AGENT_EMAIL    = "ai-red-team@vaultx.internal";

function wrapUserData(content: string): string {
  const sanitized = content
    .replace(/\[\/DATA\]/gi, "[/DATA-BLOCKED]")
    .replace(/\[SYSTEM\]/gi, "[SYSTEM-BLOCKED]");
  return `[DATA]\n${sanitized}\n[/DATA]`;
}

/* ─── Lazy provisioning: global system agent profile ─────────────────────── */

export async function getOrCreateSystemAgentProfile(): Promise<string> {
  const supabase = createAdminClient();

  const { data: existing } = await supabase
    .from("profiles")
    .select("id")
    .eq("username", SYSTEM_AGENT_USERNAME)
    .maybeSingle();

  if (existing) return existing.id;

  // Doesn't exist yet anywhere on the platform — create it once.
  // Requires the admin client since this needs a real auth.users row.
  const admin = createAdminClient();
  const { data: created, error } = await admin.auth.admin.createUser({
    email: SYSTEM_AGENT_EMAIL,
    password: randomUUID(),
    email_confirm: true,
    user_metadata: { full_name: "VAULTX AI Red Team" },
  });

  if (error || !created.user) {
    throw new Error(`Failed to provision system agent: ${error?.message}`);
  }

  await admin
    .from("profiles")
    .update({
      role: "researcher",
      username: SYSTEM_AGENT_USERNAME,
      full_name: "VAULTX AI Red Team",
      bio: "Autonomous AI agent. Findings are AI-generated hypotheses requiring human triage — same as any other submission.",
      is_onboarded: true,
      is_system_agent: true,
    })
    .eq("id", created.user.id);

  return created.user.id;
}

/* ─── Lazy provisioning: org's internal findings program ──────────────────── */

export async function getOrCreateFindingsProgram(orgId: string): Promise<string> {
  const supabase = createAdminClient();

  const { data: existing } = await supabase
    .from("programs")
    .select("id")
    .eq("org_id", orgId)
    .eq("slug", "ai-red-team-findings")
    .maybeSingle();

  if (existing) return existing.id;

  const { data: created, error } = await supabase
    .from("programs")
    .insert({
      org_id: orgId,
      slug: "ai-red-team-findings",
      name: "AI Red Team Findings",
      type: "bug_bounty",
      status: "active",
      is_public: false,
      description: "Internal program housing findings generated by AI Red Team scans. Not visible to external researchers.",
      rules: "AI-generated findings — verify before acting. Every finding requires human triage, same as any other submission.",
      scope_in: [],
      scope_out: [],
      min_reward: null,
      max_reward: null,
    })
    .select("id")
    .single();

  if (error) throw new Error(`Failed to create findings program: ${error.message}`);
  return created.id;
}

/* ─── Aggression-level prompt tuning ───────────────────────────────────────── */

const AGGRESSION_CONFIG = {
  passive:    { maxFiles: 4,  maxFindings: 4,  threshold: "only report findings you are highly confident about" },
  standard:   { maxFiles: 8,  maxFindings: 8,  threshold: "report findings with reasonable confidence, including likely-but-unconfirmed issues" },
  aggressive: { maxFiles: 14, maxFindings: 15, threshold: "report every plausible attack vector, including speculative ones — err toward over-reporting, the human triager will filter" },
} as const;

/* ─── Scan orchestrator ───────────────────────────────────────────────────── */

export interface ScanFinding {
  title: string;
  description: string;
  severity: SeverityLevel;
  confidence: number;
  attackVector: string;
}

export interface ScanOutput {
  reasoningTrace: { step: number; thought: string }[];
  findings: ScanFinding[];
}

export async function runRedTeamScan(targetId: string): Promise<{ findingsCreated: number; submissionIds: string[] }> {
  const supabase = createAdminClient();

  const { data: target } = await supabase
    .from("red_team_targets")
    .select("*")
    .eq("id", targetId)
    .single();
  if (!target) throw new Error("Target not found");

  const { data: scan } = await supabase
    .from("red_team_scans")
    .insert({ target_id: targetId, status: "running" })
    .select("id")
    .single();
  if (!scan) throw new Error("Failed to create scan record");

  try {
    const config = AGGRESSION_CONFIG[target.aggression_level as keyof typeof AGGRESSION_CONFIG];
    const output = await analyzeTarget(target, config);

    // Provision system agent + findings program (idempotent, cheap after first call)
    const [agentId, programId] = await Promise.all([
      getOrCreateSystemAgentProfile(),
      getOrCreateFindingsProgram(target.org_id),
    ]);

    const submissionIds: string[] = [];

    for (const finding of output.findings.slice(0, config.maxFindings)) {
      // Idempotency: hash target+title so re-scanning doesn't spam duplicate
      // submissions for an issue already flagged and still unresolved.
      const contentHash = createHash("sha256")
        .update(`${targetId}:${finding.title}`)
        .digest("hex");

      const { data: alreadyExists } = await supabase
        .from("submissions")
        .select("id")
        .eq("program_id", programId)
        .eq("content_hash", contentHash)
        .not("status", "in", '("rejected","wont_fix")')
        .maybeSingle();

      if (alreadyExists) continue; // already flagged and still open — skip

      const { data: submission, error } = await supabase
        .from("submissions")
        .insert({
          program_id: programId,
          researcher_id: agentId,
          title: finding.title,
          description: finding.description,
          steps_to_reproduce: `Attack vector identified by AI Red Team analysis:\n\n${finding.attackVector}\n\nThis is an AI-generated hypothesis from ${target.target_type === "github_repo" ? "static code analysis" : "threat modeling against the described scope"} — verify manually before treating as confirmed.`,
          impact: `Severity assessed by AI Red Team at ${finding.severity} with ${Math.round(finding.confidence * 100)}% confidence.`,
          severity: finding.severity,
          status: "new",
          ai_severity: finding.severity,
          ai_confidence: finding.confidence,
          ai_analysis: `AI Red Team finding from target "${target.name}" (${target.aggression_level} aggression). ${finding.attackVector}`,
          content_hash: contentHash,
          attachments: [],
        })
        .select("id")
        .single();

      if (error) { console.error(`Failed to create submission for finding: ${error.message}`); continue; }
      submissionIds.push(submission.id);
    }

    await supabase
      .from("red_team_scans")
      .update({
        status: "complete",
        reasoning_trace: output.reasoningTrace,
        findings_created: submissionIds.length,
        submission_ids: submissionIds,
        completed_at: new Date().toISOString(),
      })
      .eq("id", scan.id);

    await supabase
      .from("red_team_targets")
      .update({ last_scanned_at: new Date().toISOString() })
      .eq("id", targetId);

    return { findingsCreated: submissionIds.length, submissionIds };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Scan failed";
    await supabase
      .from("red_team_scans")
      .update({ status: "failed", error: msg, completed_at: new Date().toISOString() })
      .eq("id", scan.id);
    throw err;
  }
}

/* ─── Target analysis (the actual AI call) ────────────────────────────────── */

async function analyzeTarget(
  target: { target_type: string; target_value: string; name: string },
  config: typeof AGGRESSION_CONFIG[keyof typeof AGGRESSION_CONFIG]
): Promise<ScanOutput> {
  let contentBlock: string;

  if (target.target_type === "github_repo") {
    const parsed = parseGithubUrl(target.target_value);
    if (!parsed) throw new Error("Invalid GitHub URL");

    const meta  = await fetchRepoMetadata(parsed.owner, parsed.repo);
    const tree  = await fetchRepoTree(parsed.owner, parsed.repo, meta.defaultBranch);
    const files = await fetchFiles(parsed.owner, parsed.repo, meta.defaultBranch, tree.slice(0, config.maxFiles));

    if (files.length === 0) throw new Error("No scannable files found in repository");

    contentBlock = files.map((f) => `=== FILE: ${f.path} ===\n${f.content}`).join("\n\n");
  } else {
    contentBlock = target.target_value;
  }

  const system = `You are an offensive security researcher conducting an adversarial review, roleplaying as an attacker trying to find exploitable weaknesses — not a defensive code reviewer.

Think like an attacker: what would you target first? What assumptions might the developers have made that don't hold? Where are trust boundaries crossed without validation?

Before listing findings, write out your reasoning process as a numbered trace — your actual train of thought as you examine the target, not a polished summary.

Aggression instruction: ${config.threshold}

Respond ONLY with valid JSON. No preamble, no markdown.

JSON schema:
{
  "reasoningTrace": [{ "step": number, "thought": string }] (4-8 steps showing your actual analysis process),
  "findings": [
    {
      "title": string,
      "description": string (what the vulnerability is and where),
      "severity": "critical" | "high" | "medium" | "low" | "info",
      "confidence": number (0.0 to 1.0),
      "attackVector": string (how an attacker would actually exploit this, specific and concrete)
    }
  ]
}

Maximum ${config.maxFindings} findings, prioritized by severity.`;

  const user = `Target: ${target.name}
Type: ${target.target_type === "github_repo" ? "Source code repository" : "Described system scope"}

${wrapUserData(contentBlock.slice(0, 20000))}

Conduct your adversarial analysis and return JSON.`;

  const message = await callClaude({ system, user, maxTokens: 3000, temperature: 0.4 });
  const parsed = parseJsonResponse<ScanOutput>(message);

  return {
    reasoningTrace: Array.isArray(parsed.reasoningTrace) ? parsed.reasoningTrace : [],
    findings: Array.isArray(parsed.findings) ? parsed.findings : [],
  };
}
